/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlUsuarioPila;
import controlador.controlUsuarioPila.Nodo;
import gestorArchivos.gestorUsuario;
import java.awt.HeadlessException;
import java.util.Properties;
import java.util.StringTokenizer;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.usuarioLogin;

/**
 *
 * @author ferna
 */
public class frmRegistroLogin extends javax.swing.JFrame {

    DefaultTableModel modelo;
    String[] cabecera = {"IDENTIFICADOR", "USUARIO", "CONSTRASEÑA"};
    String[][] data = {};
    int num = 0, tam;
    gestorUsuario gestor = new gestorUsuario();
    String FileName = "login.bin";
    controlUsuarioPila lista = new controlUsuarioPila();
    Nodo nodo;

    /**
     * Creates new form frmRegistroLogin
     */
    public frmRegistroLogin() {
        initComponents();
        gestor.AbrirArchivo(FileName, lista);
        tam = 0;
        modelo = new DefaultTableModel(data, cabecera);
        tablaDatos.setModel(modelo);
        verdatos();
        this.setLocationRelativeTo(null);
        this.setTitle("REGISTRO DE USUARIOS");
        tablaDatos.setEnabled(false);
        this.setResizable(false);
    }

    //METODOS LOCOS
    public String Eliminar() {
        String eliminado = "";
        Nodo aux = lista.inicio;
        String usu = aux.getUsu().getUsuario();
        String pass = aux.getUsu().getPassword();
        eliminado = usu + "," + String.valueOf(pass);
        lista.inicio = lista.inicio.getSigui();
        aux.setSigui(null);
        return eliminado;

    }

    public void mensaje(String data) {
        StringTokenizer st = new StringTokenizer(data, ",");
        String usu = st.nextToken();
        String pass = st.nextToken();

        String datos = "DETALLES DEL USUARIO ELIMINADO:\n"
                + "-->USUARIO:" + usu + "\n"
                + "-->CONSTRASEÑA:" + pass + "\n";
        JOptionPane.showMessageDialog(this, datos);
    }

    void vaciartabla() {
        int filas = tablaDatos.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }

    public int Numelem() {
        int num = 0;
        Nodo aux = lista.inicio;
        while (aux != null) {
            num++;
            aux = aux.getSigui();
        }
        return num;
    }

    public void verdatos() {
        String usuar;
        String passwor;
        Nodo aux = lista.inicio;
        vaciartabla();
        Nodo p;
        num = Numelem();
        while (aux != null) {
            usuar = aux.getUsu().getUsuario();
            passwor = aux.getUsu().getPassword();

            Object[] fila = {num, usuar, passwor};
            num--;
            modelo.addRow(fila);
            aux = aux.getSigui();
        }
    }

    public Nodo Buscar(Nodo tope, String usuar) {
        Nodo pos = tope;
        while (pos != null && !usuar.equalsIgnoreCase(pos.getUsu().getUsuario())) {
            pos = pos.getSigui();
        }
        return pos;
    }

    public Nodo Buscar2(Nodo tope, String passwor) {
        Nodo pos = tope;
        while (pos != null && !passwor.equalsIgnoreCase(String.valueOf(pos.getUsu().getPassword()))) {
            pos = pos.getSigui();
        }
        return pos;
    }

    void limpiacampos() {
        txtusuario.setText("");
        txtcontrasena.setText("");
        txtusuario.requestFocus();
        txtcorreo.setText("");
        txtverificar.setText("");

    }

    void habilitar() {
        btnguardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtverificar = new javax.swing.JTextField();
        btnverificarCorreo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnatras = new javax.swing.JButton();
        btnborrrartodo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(17, 71, 17));

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO:");

        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CONTRASEÑA:");

        jLabel4.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CORREO:");

        jLabel5.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero:");

        txtcontrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtcontrasena.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        txtcontrasena.setForeground(new java.awt.Color(0, 0, 0));

        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 0, 0));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(0, 0, 0));

        txtverificar.setBackground(new java.awt.Color(255, 255, 255));
        txtverificar.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        txtverificar.setForeground(new java.awt.Color(0, 0, 102));

        btnverificarCorreo.setBackground(new java.awt.Color(255, 255, 255));
        btnverificarCorreo.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        btnverificarCorreo.setForeground(new java.awt.Color(153, 0, 0));
        btnverificarCorreo.setText("Verificar Correo");
        btnverificarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificarCorreoActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_102938.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnatras.setBackground(new java.awt.Color(255, 255, 255));
        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrowback_257.png"))); // NOI18N
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnborrrartodo.setBackground(new java.awt.Color(255, 255, 255));
        btnborrrartodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/business_deletethedatabase_exit_db_delete_busines_2346.png"))); // NOI18N
        btnborrrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrrartodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtusuario))
                        .addGap(57, 57, 57)
                        .addComponent(btnverificarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtverificar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnborrrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnverificarCorreo)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtverificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnborrrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnatras, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tablaDatos.setBackground(new java.awt.Color(23, 62, 23));
        tablaDatos.setFont(new java.awt.Font("Eras Light ITC", 3, 14)); // NOI18N
        tablaDatos.setForeground(new java.awt.Color(255, 255, 255));
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnverificarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificarCorreoActionPerformed
        // TODO add your handling code here:
        Properties p = new Properties();
        p.setProperty("mail.smtp.host", "smtp.gmail.com");
        p.setProperty("mail.smtp.starttls.enable", "true");
        p.setProperty("mail.smtp.port", "587");
        p.setProperty("mail.smtp.auth", "true");

        Session sesion = Session.getDefaultInstance(p, null);

        String correoEnvia = "sistemagestiontercerciclo@gmail.com";
        String contrasena = "diegolojan99";
        String destinatario = txtcorreo.getText();
        String asunto = "VERIFICACION DE REGISTRO";
        String mensaje = "HOLA,ESTE ES UN MENSAJE DE VERIFICACION, INGRESE LOS SIGUIENTES NUMEROS EN EL CAMPO NUMERO\n\n\t---448975215---";

        MimeMessage mail = new MimeMessage(sesion);

        try {
            mail.setFrom(new InternetAddress(correoEnvia));
            mail.addRecipient(Message.RecipientType.TO, new InternetAddress(destinatario));
            mail.setSubject(asunto);
            mail.setText(mensaje);

            Transport trasporte = sesion.getTransport("smtp");
            trasporte.connect(correoEnvia, contrasena);
            trasporte.sendMessage(mail, mail.getRecipients(Message.RecipientType.TO));
            trasporte.close();

            JOptionPane.showMessageDialog(null, "CORREO ENVIADO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | MessagingException e) {
            JOptionPane.showMessageDialog(null, "ERROR DE ENVIO", "ALERTA", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnverificarCorreoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:

        if (txtusuario.getText().isEmpty() && txtcontrasena.getText().isEmpty() && txtcorreo.getText().isEmpty() && txtverificar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡DEBE LLENAR TODOS LOS DATOS!", "ALERTA", JOptionPane.WARNING_MESSAGE);
        }
        else if (!txtverificar.getText().equals("448975215")) {
            JOptionPane.showMessageDialog(null, "¡ERROR AL VERIFICAR!", "ALERTA", JOptionPane.WARNING_MESSAGE);
        } else {
            String usuar = txtusuario.getText();
            String passwor = txtcontrasena.getText();
            lista.push(new usuarioLogin(new Object[]{usuar, passwor}));
            try {
                StringBuffer usuarios = new StringBuffer(txtusuario.getText().trim() + " " + txtcontrasena.getText().trim() + "\t");
                gestorUsuario.EscribeTxt(usuarios);
            } catch (Exception e) {
            }
            tam = tam + 1;
            limpiacampos();
            verdatos();
            gestor.GrabarArchivo(FileName, lista);

        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if (lista.inicio == null) {
            JOptionPane.showMessageDialog(this, "¡PILA VACIA!");
            txtusuario.requestFocus();
        } else {
            String dato = Eliminar();
            mensaje(dato);
            gestor.GrabarArchivo(FileName, lista);
            verdatos();
            limpiacampos();
            if (lista.inicio == null) {
                JOptionPane.showMessageDialog(this, "¡PILA VACIA!");
            }

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String usuar = txtusuario.getText();
        if (usuar.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "INGRESE UN NOMBRE EN EL CAMPO USUARIO", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            txtusuario.requestFocus();
        } else {
            lista.nodo1 = Buscar(lista.inicio, usuar);
            if (lista.nodo1 != null) {
                txtusuario.setText(lista.nodo1.getUsu().getUsuario());
                txtcontrasena.setText(String.valueOf(lista.nodo1.getUsu().getPassword()));
                habilitar();
            } else {
                JOptionPane.showMessageDialog(this, "EL USUARIO: " + usuar + " NO ESTA EN LA PILA");
            }
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        // TODO add your handling code here:
        frmLogin loyin = new frmLogin();
        loyin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnborrrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrrartodoActionPerformed
        // TODO add your handling code here:
        vaciartabla();
    }//GEN-LAST:event_btnborrrartodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnborrrartodo;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnverificarCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txtcontrasena;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JTextField txtverificar;
    // End of variables declaration//GEN-END:variables
}
